In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
tf.__version__

Instructions for updating:
non-resource variables are not supported in the long term


'2.4.0'

In [2]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [3]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [4]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)


In [5]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [6]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  227.97383 
Prediction:
 [[157.55943]
 [204.47334]
 [193.45486]
 [214.47198]
 [156.40497]]
10 Cost:  16.524677 
Prediction:
 [[144.7125 ]
 [189.00519]
 [178.22798]
 [197.88776]
 [144.602  ]]
20 Cost:  16.451357 
Prediction:
 [[144.68796]
 [188.94867]
 [178.18643]
 [197.83997]
 [144.55428]]
30 Cost:  16.380386 
Prediction:
 [[144.70216]
 [188.9388 ]
 [178.1908 ]
 [197.8422 ]
 [144.54214]]
40 Cost:  16.30975 
Prediction:
 [[144.71645]
 [188.92908]
 [178.19528]
 [197.84454]
 [144.53014]]
50 Cost:  16.239521 
Prediction:
 [[144.73071]
 [188.91942]
 [178.19977]
 [197.84692]
 [144.51819]]
60 Cost:  16.169662 
Prediction:
 [[144.74492]
 [188.90976]
 [178.20424]
 [197.84927]
 [144.50626]]
70 Cost:  16.100132 
Prediction:
 [[144.7591 ]
 [188.90012]
 [178.20868]
 [197.8516 ]
 [144.49435]]
80 Cost:  16.03096 
Prediction:
 [[144.77324]
 [188.8905 ]
 [178.21313]
 [197.85394]
 [144.48248]]
90 Cost:  15.962221 
Prediction:
 [[144.78734]
 [188.88094]
 [178.21758]
 [197.85628]
 [144.47066]]
100