In [22]:
import tensorflow.compat.v1 as tf
import warnings
tf.disable_v2_behavior()
tf.set_random_seed(777)  # for reproducibility
warnings.filterwarnings('ignore')
print(tf.__version__)

2.4.0


In [23]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]


In [24]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

In [25]:
# tf.nn.softmax computes softmax activations
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [26]:
# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [27]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [28]:
for step in range(201):
    cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
    print(step, cost_val, W_val)

 -0.5446307  -0.11099736]
 [-1.1293329  -1.1902728  -2.0087543 ]]
50 1.0125592 [[ 1.2584465   0.8396029  -0.15197727]
 [-0.7641911  -0.5497598  -0.11686317]
 [-1.135442   -1.1855378  -2.0073802 ]]
51 1.0047312 [[ 1.2466841   0.8399811  -0.14059314]
 [-0.7535179  -0.55461663 -0.12267952]
 [-1.1412961  -1.1810523  -2.0060115 ]]
52 0.99715465 [[ 1.2350454   0.84031886 -0.1292923 ]
 [-0.7431582  -0.5592097  -0.12844616]
 [-1.1469018  -1.1768084  -2.0046499 ]]
53 0.98981804 [[ 1.2235287   0.8406177  -0.11807451]
 [-0.7331042  -0.56354684 -0.13416302]
 [-1.1522664  -1.172797   -2.0032966 ]]
54 0.98271006 [[ 1.2121325   0.840879   -0.10693952]
 [-0.7233473  -0.5676368  -0.13983   ]
 [-1.1573964  -1.16901    -2.0019534 ]]
55 0.9758191 [[ 1.2008547   0.8411043  -0.09588701]
 [-0.7138794  -0.57148767 -0.14544697]
 [-1.1622995  -1.1654389  -2.0006213 ]]
56 0.969136 [[ 1.1896936   0.84129506 -0.08491666]
 [-0.70469165 -0.5751084  -0.15101402]
 [-1.1669822  -1.1620756  -1.9993019 ]]
57 0.9626502 [[

In [29]:
# predict
print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
# Calculate the accuracy
print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))


Prediction: [2 2 2]
Accuracy:  1.0
