In [10]:
import tensorflow.compat.v1 as tf
import warnings
tf.disable_v2_behavior()
tf.set_random_seed(777)  # for reproducibility
warnings.filterwarnings('ignore')
print(tf.__version__)

2.4.0


In [11]:
import numpy as np

In [12]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [13]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [14]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [15]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [16]:
for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  468727820000.0 
Prediction:
 [[483421.66]
 [973444.06]
 [765719.4 ]
 [536688.44]
 [632562.25]
 [637885.1 ]
 [584626.25]
 [744408.4 ]]
1 Cost:  5.149822e+26 
Prediction:
 [[-1.6007644e+13]
 [-3.2225028e+13]
 [-2.5350266e+13]
 [-1.7770402e+13]
 [-2.0943370e+13]
 [-2.1119646e+13]
 [-1.9356887e+13]
 [-2.4645164e+13]]
2 Cost:  inf 
Prediction:
 [[5.3059493e+20]
 [1.0681420e+21]
 [8.4026881e+20]
 [5.8902393e+20]
 [6.9419618e+20]
 [7.0003903e+20]
 [6.4161004e+20]
 [8.1689710e+20]]
3 Cost:  inf 
Prediction:
 [[-1.7587284e+28]
 [-3.5405008e+28]
 [-2.7851842e+28]
 [-1.9523994e+28]
 [-2.3010068e+28]
 [-2.3203740e+28]
 [-2.1267031e+28]
 [-2.7077157e+28]]
4 Cost:  inf 
Prediction:
 [[5.8295432e+35]
 [1.1735468e+36]
 [9.2318691e+35]
 [6.4714914e+35]
 [7.6269981e+35]
 [7.6911927e+35]
 [7.0492449e+35]
 [8.9750898e+35]]
5 Cost:  inf 
Prediction:
 [[-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]]
6 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
