In [9]:
import tensorflow.compat.v1 as tf
import warnings
tf.disable_v2_behavior()
tf.set_random_seed(777)  # for reproducibility
warnings.filterwarnings('ignore')
print(tf.__version__)

2.4.0


In [10]:
import numpy as np

In [11]:
# very important. It does not work without it.
def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [12]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

xy = min_max_scaler(xy)
print(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [13]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [14]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [15]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [16]:
for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  3.6646028 
Prediction:
 [[1.8959911]
 [2.5416574]
 [2.4825053]
 [2.3672247]
 [2.4103918]
 [2.2758195]
 [2.5631897]
 [2.4086664]]
1 Cost:  3.6643744 
Prediction:
 [[1.8959091]
 [2.5415735]
 [2.4824347]
 [2.367169 ]
 [2.410327 ]
 [2.2757566]
 [2.5631442]
 [2.4086204]]
2 Cost:  3.664146 
Prediction:
 [[1.8958268]
 [2.5414896]
 [2.482364 ]
 [2.3671134]
 [2.410262 ]
 [2.2756937]
 [2.5630984]
 [2.408574 ]]
3 Cost:  3.6639178 
Prediction:
 [[1.8957448]
 [2.5414057]
 [2.4822931]
 [2.3670578]
 [2.4101973]
 [2.2756307]
 [2.563053 ]
 [2.408528 ]]
4 Cost:  3.6636896 
Prediction:
 [[1.8956625]
 [2.5413218]
 [2.4822226]
 [2.367002 ]
 [2.4101326]
 [2.2755678]
 [2.5630074]
 [2.4084818]]
5 Cost:  3.6634614 
Prediction:
 [[1.8955805]
 [2.541238 ]
 [2.482152 ]
 [2.3669462]
 [2.4100678]
 [2.2755048]
 [2.5629616]
 [2.4084358]]
6 Cost:  3.663233 
Prediction:
 [[1.8954983]
 [2.541154 ]
 [2.4820814]
 [2.3668904]
 [2.4100032]
 [2.275442 ]
 [2.562916 ]
 [2.4083896]]
7 Cost:  3.663005 
Prediction:
 [[1.