In [2]:
import tensorflow.compat.v1 as tf
import warnings
tf.disable_v2_behavior()
tf.set_random_seed(777)  # for reproducibility
warnings.filterwarnings('ignore')
print(tf.__version__)

Instructions for updating:
non-resource variables are not supported in the long term
2.4.0


In [3]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [4]:
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

In [5]:
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [6]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [7]:
for step in range(2001):
        _, cost_val = sess.run([optimizer, cost], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, cost_val)

0 [[9.7013377e-03 1.9392589e-01 7.9637271e-01]
 [2.2781009e-02 5.4873288e-01 4.2848614e-01]
 [2.7644256e-04 2.0819117e-01 7.9153240e-01]
 [3.7236826e-04 5.6374985e-01 4.3587774e-01]
 [7.3393567e-06 2.6149851e-01 7.3849422e-01]
 [1.0364375e-05 1.6213277e-01 8.3785689e-01]
 [4.2551410e-06 3.1143281e-01 6.8856293e-01]
 [8.0199180e-07 3.3558592e-01 6.6441327e-01]]
200 [[8.3801262e-03 4.1274261e-02 9.5034564e-01]
 [7.9034686e-02 1.8505129e-01 7.3591399e-01]
 [1.6253542e-03 2.0488799e-01 7.9348671e-01]
 [1.0680303e-02 5.3050208e-01 4.5881757e-01]
 [8.2706690e-01 1.3488285e-01 3.8050219e-02]
 [4.0113920e-01 5.7065469e-01 2.8206099e-02]
 [8.9951479e-01 9.5459759e-02 5.0254730e-03]
 [9.5399469e-01 4.5261856e-02 7.4342819e-04]]
400 [[1.5680407e-03 2.1207159e-02 9.7722477e-01]
 [3.1412970e-02 1.3885885e-01 8.2972813e-01]
 [2.4461874e-04 2.1795160e-01 7.8180385e-01]
 [2.1248215e-03 6.0883576e-01 3.8903940e-01]
 [7.3157406e-01 2.3532063e-01 3.3105373e-02]
 [3.7837532e-01 6.1388814e-01 7.7364640e-03

In [8]:
print('--------------')
# Testing & One-hot encoding
a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
print(a, sess.run(tf.argmax(a, 1)))

print('--------------')
b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
print(b, sess.run(tf.argmax(b, 1)))

print('--------------')
c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
print(c, sess.run(tf.argmax(c, 1)))

print('--------------')
all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
print(all, sess.run(tf.argmax(all, 1)))


--------------
[[2.6234693e-03 9.9736720e-01 9.3491308e-06]] [1]
--------------
[[0.88711476 0.09701805 0.01586713]] [0]
--------------
[[5.4152314e-09 2.7104167e-04 9.9972898e-01]] [2]
--------------
[[2.6234693e-03 9.9736720e-01 9.3491126e-06]
 [8.8711488e-01 9.7018041e-02 1.5867127e-02]
 [5.4152314e-09 2.7104141e-04 9.9972898e-01]] [1 0 2]
